apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow-community-1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/jokam85/airflow-community-chart.git'
    path: 'charts/airflow'
    targetRevision: 'airflow-8.5.2'
    helm:
      releaseName: 'airflow'
      parameters:
        - name: 'airflow.executor'
          value: 'KubernetesExecutor'
          
        - name: airflow.fernetKey
          value: ''
          
        - name: 'redis.enabled'
          value: 'false'
        - name: 'workers.enabled'
          value: 'false'
        - name: 'flower.enabled'
          value: 'false'
        - name: 'rbac.create'
          value: 'true'
        - name: 'serviceaccount.create'
          value: 'true'
          
        - name: airflow.config.AIRFLOW__WEBSERVER__BASE_URL
          value: '/airflowc'
        - name: airflow.config.AIRFLOW__CORE__LOAD_EXAMPLES
          value: 'True'
        - name: airflow.config.AIRFLOW__WEBSERVER__EXPOSE_CONFIG
          value: 'True'

        - name: 'ingress.enabled'
          value: 'true'
        - name: 'ingress.web.host'
          value: 'localhost'
        - name: 'ingress.web.path'
          value: '/airflowc'
          
        - name: 'postgresql.enabled'
          value: 'true'
          
        - name: 'airflow.variables[0].key'
          value: 'var_1'
        - name: 'airflow.variables[0].value'
          value: 'var_1_value_new'
          
        - name: 'airflow.variables[1].key'
          value: 'var_2'
        - name: 'airflow.variables[1].value'
          value: 'var_2_value'
          
        - name: 'web.extraPipPackages[0]'
          value: 'Flask-AppBuilder~=3.3.0'
        - name: 'web.extraPipPackages[1]'
          value: 'Authlib~=0.15.3'

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ac1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
