apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/bitnami/charts.git'
    path: 'bitnami/airflow'
    targetRevision: HEAD
    helm:
      releaseName: 'keycloak'
      parameters:
        - name: ''
          value: ''
        - name: ''
          value: ''
        - name: ''
          value: ''
        - name: ''
          value: ''
        - name: ''
          value: ''
        - name: ''
          value: ''
        - name: ''
          value: ''
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
