apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow-community-1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/jokam85/airflow-community-chart.git'
    path: 'charts/airflow'
    targetRevision: 'airflow-8.5.2'
    helm:
      releaseName: 'airflow'
      parameters:
        - name: 'airflow.executor'
          value: 'KubernetesExecutor'
        - name: airflow.fernetKey
          value: ''
          
        - name: 'redis.enabled'
          value: 'false'
          
        - name: 'workers.enabled'
          value: 'false'
          
        - name: 'flower.enabled'
          value: 'false'
          
        - name: 'rbac.create'
          value: 'true'
          
        - name: 'serviceaccount.create'
          value: 'true'
          
        - name: airflow.config.AIRFLOW__WEBSERVER__BASE_URL
          value: '/airflowc'
          
        - name: airflow.config.AIRFLOW__CORE__LOAD_EXAMPLES
          value: 'True'

        - name: 'ingress.enabled'
          value: 'true'
        - name: 'ingress.web.host'
          value: 'localhost'
        - name: 'ingress.web.path'
          value: '/airflowc'
          
#         - name: 'postgresql.enabled'
#           value: 'false'
#         - name: 'externalDatabase.host'
#           value: 'postgres-postgresql.postgresql.svc.cluster.local'
#         - name: 'externalDatabase.user'
#           value: 'airflow'
#         - name: 'externalDatabase.password'
#           value: 'airflow'
#         - name: 'externalDatabase.port'
#           value: '5432'
#         - name: 'externalDatabase.database'
#           value: 'ac1'

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ac1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
