apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/bitnami/charts.git'
    path: 'bitnami/airflow'
    targetRevision: HEAD
    helm:
      releaseName: 'airflow'
      parameters:
        - name: 'executor'
          value: 'KubernetesExecutor'
        - name: 'redis.enabled'
          value: 'false'
        - name: 'rbac.create'
          value: 'true'
        - name: 'serviceaccount.create'
          value: 'true'
        - name: 'web.baseUrl'
          value: '/airflow'
          
        - name: 'ingress.enabled'
          value: 'true'
        - name: 'ingress.hosts[0].name'
          value: 'localhost'
        - name: 'ingress.hosts[0].path'
          value: '/airflow'
          
        - name: 'postgresql.enabled'
          value: 'false'
        - name: 'externalDatabase.host'
          value: 'postgres-postgresql.postgresql.svc.cluster.local'
        - name: 'externalDatabase.user'
          value: 'airflow'
        - name: 'externalDatabase.password'
          value: 'airflow'
        - name: 'externalDatabase.port'
          value: '5432'
        - name: 'externalDatabase.database'
          value: 'airflow2'
          
        - name: 'auth.username'
          value: 'user'
        - name: 'auth.password'
          value: 'user'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
