apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm-2
  namespace: argocd
data:
  url: http://localhost
  oidc.config: |
    name: Keycloak
    issuer: http://localhost/auth/realms/argocd
    clientID: argocd
    clientSecret: $oidc.keycloak.clientSecret
    requestedScopes: ["openid", "profile", "email", "groups"]
