apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`localhost`) && Path(`/argo-cd`)
      priority: 10
#       middlewares:
#         - stripprefix
      services:
        - name: argocd-server
          port: 80
    - kind: Rule
      match: Host(`localhost`) && Path(`/argo-cd`) && Headers(`Content-Type`, `application/grpc`)
      priority: 11
#       middlewares:
#         - stripprefix
      services:
        - name: argocd-server
          port: 80
          scheme: h2c
---
# apiVersion: traefik.containo.us/v1alpha1
# kind: Middleware
# metadata:
#   name: stripprefix
# spec:
#   stripPrefix:
#     prefixes:
#       - /argo-cd
