apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/bitnami/charts.git'
    path: 'bitnami/keycloak'
    targetRevision: HEAD
    helm:
      releaseName: 'keycloak'
      parameters:
        - name: 'auth.adminUser'
          value: 'admin'
        - name: 'auth.adminPassword'
          value: 'admin'
          
        - name: 'service.type'
          value: 'ClusterIP'
        - name: 'ingress.path'
          value: '/auth'
          
        - name: 'postgresql.enabled	'
          value: 'false'
        - name: 'externalDatabase.host'
          value: 'postgres-postgresql.postgresql.svc.cluster.local'         
        - name: 'externalDatabase.port'
          value: '5432'         
        - name: 'externalDatabase.user'
          value: 'keycloak'         
        - name: 'externalDatabase.password'
          value: 'keycloak'         
        - name: 'externalDatabase.database'
          value: 'postgres'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
